name: Deploy

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    name: Configuração, Instalação e Deploy para AWS
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: api
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install annotated-types==0.7.0 anyio==4.8.0 asyncpg==0.30.0 click==8.1.8 colorama==0.4.6 fastapi==0.115.11 greenlet==3.1.1 h11==0.14.0 idna==3.10 psycopg2-binary==2.9.10 pydantic==2.10.6 pydantic_core==2.27.2 sniffio==1.3.1 SQLAlchemy==2.0.38 starlette==0.46.1 typing_extensions==4.12.2 uvicorn==0.34.0

      - name: Verificar instalação das dependências
        run: |
          pip list

      - name: Copiar arquivos para o servidor AWS via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rltgoDzvo --delete"
          SOURCE: "./"
          REMOTE_HOST: "ec2-13-216-63-207.compute-1.amazonaws.com
          REMOTE_USER: "ec2-user"
          TARGET: "home/ec2-user"